################################  启用配置文件  ################################
spring:
  application:
    name: Xin-Admin-Web
  profiles:
    active: dev

###################  spring boot 启用actuator监控配置  ###################

info:
  head: Actuator is running
  body: X-Admin-Web
  version: Xin-Admin-Web 0.0.1-SNAPSHOT
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#详情参考https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/actuator-api/html/
#  auditevents	显示当前应用程序的审计事件信息
#  beans	显示应用Spring Beans的完整列表
#  caches	显示可用缓存信息
#  conditions	显示自动装配类的状态及及应用信息
#  configprops	显示所有 @ConfigurationProperties 列表
#  env	显示 ConfigurableEnvironment 中的属性
#  flyway	显示 Flyway 数据库迁移信息
#  health	显示应用的健康信息（未认证只显示status，认证显示全部信息详情
#  info	显示任意的应用信息（在资源文件写info.xxx即可）
#  liquibase	展示Liquibase 数据库迁移
#  metrics	展示当前应用的 metrics 信息
#  mappings	显示所有 @RequestMapping 路径集列表
#  scheduledtasks	显示应用程序中的计划任务
#  sessions	允许从Spring会话支持的会话存储中检索和删除用户会话。
#  shutdown	允许应用以优雅的方式关闭（默认情况下不启用）
#  threaddump	执行一个线程dump
#  httptrace	显示HTTP跟踪信息（默认显示最后100个HTTP请求 - 响应交换）
